grammar Oglavleniye;

probelniy: PROBEL | TABYLACIYA | PROBELNIY;

PROBEL: ' ';
TOCHKA: '.';
COMMA: ',';
NL: '\n';
TABYLACIYA: '\t';
PROBELNIYODIN: PROBEL | TABYLACIYA;
PROBELNIY: (PROBEL | TABYLACIYA)+;

//fragment UTF8CHARSET1: [\u0000-\u007f];
fragment UTF8CHARSET2: [\u0080-\u07FF];
fragment UTF8CHARSET3: [\u0800-\uFFFF];
fragment UTF8CHARSET4: [\u10000-\u10FFFF];

UTF8CHARSET: (UTF8CHARSET2 | UTF8CHARSET3 | UTF8CHARSET4)+;